units:
  # choc spacing
  # cx = 18
  # cy = 17
  # choc spacing with padding
  px: cx + 2
  py: cy + 2
  # keycap size
  kcx: 17.5
  kcy: 16.5
  # keycap size with padding
  kdx: kcx + 2.5
  kdy: kcy + 2.5
  # switch hole
  switch_x: 13.6 + 0.3
  switch_y: 13.8 + 0.3
  # mcu dimensions
  mcux: 18
  mcuy: 33
  # mcu coordinates
  mcsx: 1.065px
  mcsy: -kcy/2-2
  # reset switch dimensions
  rsx: 3.5
  rsy: 6.1
  rsh: 1.3 # hole diameter
  rsd: 6.5 # distance between holes
  # screw hole diameter (M2)
  # screw head diameter ~3.3
  # M2 nut height ~1.5
  scd: 2.2
  # TRRS connector
  trx: 6.1
  try: 12.1
  # trackpoint mount
  tpm_x: 7.8
  tpm_y: 23.3

points:
  zones:
    matrix:
      key:
        width: kcx
        height: kcy
        padding: cy
        spread: cx
      anchor:
        # Fix placement on KiCAD sheet.
        shift: [100, -100]
        # rotate: -20
      columns:
        pinky:
          key:
            column_net: C1
        ring:
          key:
            column_net: C2
            stagger: 10 # was 4
            splay: -5
            origin: [0, -3]
        middle:
          key:
            column_net: C3
            stagger: 2
            splay: -5
        index:
          key:
            column_net: C4
            stagger: -2
        inner:
          rows:
            home:
              adjust:
                rotate: 180
          key:
            column_net: C5
            stagger: -2
      rows:
        bottom:
          row_net: R3
        home:
          row_net: R2
        top:
          row_net: R1
        num:
          row_net: R0
    thumb:
      key:
        width: kcx
        height: kcy
        padding: cy
        spread: cx
      anchor:
        ref: matrix_inner_bottom
        shift: [-10, -20]
      columns:
        flexion:
          key:
            column_net: C4
            splay: -15
          rows:
            upper:
              skip: true
        base:
          key:
            column_net: C5
          rows:
            upper:
              shift: [5, 5]
        extension:
          key:
            column_net: C6
          rows:
            upper:
              skip: true
      rows:
        lower:
          row_net: R4
        upper:
          row_net: R3
    # mcu:
    #   anchor:
    #     ref: matrix_inner_num
    #     shift: [mcsx,mcsy]
    # reset:
    #   anchor:
    #     ref: mcu
    #     shift: [(0.5mcux)-(0.5rsx),(-0.5mcuy)-(0.5rsy)-4]
    # power:
    #   anchor:
    #     ref: reset
    #     shift: [0.025,-1.5rsy]
    # screw_pcb_pinky_top:
      # anchor:
        # - ref: matrix_pinky2_num
          # shift: [0.5*18,0.45*17]
    # trrs:
    #   anchor:
    #     ref: mcu
    #     shift: [0.85mcux,0.475mcuy+2]
      # key:
      #   width: tpm_x
      #   height: tpm_y

  #mirror: #mirroring section only here for paper print testing
  #  ref: matrix_pinky_home
  #  distance: 250
outlines:
  pinky:
    - what: rectangle
      where: -/matrix_pinky/
      size: [kdx, kdy]
      fillet: 0.5
  ring:
    - what: rectangle
      where: -/matrix_ring/
      size: [kdx, kdy]
      fillet: 0.5
  middle:
    - what: rectangle
      where: -/matrix_middle/
      size: [kdx, kdy]
      fillet: 0.5
  index:
    - what: rectangle
      where: -/matrix_index/
      size: [kdx, kdy]
      fillet: 0.5
  inner:
    - what: rectangle
      where: -/matrix_inner/
      size: [kdx, kdy]
      fillet: 0.5
  thumb:
    - what: rectangle
      where: -/thumb/
      size: [kdx, kdy]
      fillet: 0.5
  matrix_thumb:
    - name: pinky
    - name: ring
    - name: middle
    - name: index
    - name: inner
    - name: thumb
  plate_helper_shape:
    - what: polygon
      operation: stack
      fillet: 0.5
      points:
        # top
        # pinky
        # - ref: matrix_pinky_num
        # - ref: matrix_ring_num
        # - ref: matrix_middle_num
        # - ref: matrix_index_num
        # - ref: matrix_inner_num
        - ref: matrix_inner_bottom
          shift: [0.5kdx, 0.5kdy]
        - ref: thumb_base_upper
          shift: [-0.5kdx, 0.5kdy]
        - ref: thumb_base_upper
          shift: [0.5kdx, 0.5kdy]
        - ref: thumb_base_upper
          shift: [0.5kdx, -0.5kdy]
        - ref: thumb_extension_lower
          shift: [0.5kdx, 0.5kdy]
        - ref: thumb_extension_lower
          shift: [0.5kdx, -0.5kdy]
        - ref: thumb_flexion_lower
          shift: [-0.5kdx, -0.5kdy]
        - ref: thumb_flexion_lower
          shift: [-0.5kdx, 0.5]
        - ref: matrix_index_bottom
          shift: [0.15kdx, -0.5]
        # - ref: matrix_pinky_home
  keycaps:
    - what: rectangle
      where:
        - /matrix/
        - /thumb/
      size: [kcx, kcy]
  plate_shape:
    - name: matrix_thumb
    - name: plate_helper_shape
  preview:
    - name: plate_shape
    - name: keycaps
      operation: subtract
  switch_cutouts:
    - what: rectangle
      where:
        - /matrix/
        - /thumb/
      size: [switch_x, switch_y]
  test_print:
    - name: plate_shape
    - name: switch_cutouts
      operation: subtract
  # mcu:
  #   - what: rectangle
  #     where:
  #       ref: mcu
  #     size: [mcux,mcuy]
  # power:
  #   - what: rectangle
  #     where:
  #       ref: reset
  #     adjust:
      #   shift: [0,-0.7rsy]
      # size: [rsx,rsy]
  # reset:
  #   - what: rectangle
  #     where:
  #       ref: reset
  #     size: [rsx,rsy]
  # screws:
  #   - what: circle
  #     where: /screw_pcb/
  #     radius: 0.5scd
  # trrs:
  #   - what: rectangle
  #     where:
  #       ref: trrs
  #     size: [trx,try]
  # pcb:
  #   - name: plate
  #   - name: screws
  #     operation: subtract
  # case_inner:
  #   - name: pcb
  #     expand: 0.7
  #   - name: screws
  #     operation: subtract
  # case_outer:
  #   - name: pcb
  #     expand: 2.7
  #   - name: screws
  #     operation: subtract
  # case_top_inner:
  #   - name: pcb
  #     expand: 0.7
  #   - name: screws
  #     operation: subtract
  #   - name: switch_cutouts
  #     operation: subtract
  #   - name: mcu
  #     operation: subtract
  #   - name: reset
  #     operation: subtract
  # case_top_outer:
  #   - name: pcb
  #     expand: 2.7
  #   - name: screws
  #     operation: subtract
  #   - name: switch_cutouts
  #     operation: subtract
  #   - name: mcu
  #     operation: subtract
  #   - name: reset
  #     operation: subtract
pcbs:
  deadpoint:
    outlines:
      main:
        outline: plate_shape
    footprints:
      # mcu
      mcu:
        what: infused-kim/nice_nano_pretty
        where:
          ref.aggregate.parts: [matrix_inner_num]
          shift: [mcsx,mcsy]
        params:
          traces: true
          show_via_labels: true
          show_silk_labels: true
          show_instructions: true

          # pin assignments (controller on top, components facing down)
          # right column
          P1: SP # serial pin
          P0: D1
          # GND
          # GND
          P2: C0
          P3: C1
          P4: C2
          P5: C3
          P6: C4
          P7: C5
          P8: C6
          P9: C7


          # left column
          # RAW
          # GND
          # RST (RUN)
          # VCC
          P21: DATA # A3
          P20: CLK # A2
          P19: TPR # trackpoint reset
          P18: R0
          P15: R1
          P14: R2
          P16: R3
          P10: R4
      choc_hotswap:
        what: infused-kim/choc
        where:
          - /matrix/
          - /thumb/
        adjust.rotate: 180 # orient choc footprint properly
        params:
          show_keycaps: true # shows the outline of the keycap width x depth bounding box
          keycaps_x: kcx
          keycaps_y: kcy
          reverse: true # determines if the footprint appears on the top and bottom of the pcb.
          hotswap: true # use the hotswap footprint instead of through-hole
          from: "{{column_net}}"
          to: "{{colrow}}"
      diode:
        what: infused-kim/diode
        where:
          - /matrix/
          - /thumb/
        params:
          from: "{{colrow}}"
          to: "{{row_net}}"
        adjust:
          shift: [-7.8, 2]
          rotate: 90 # makes diode arrow point down
      # power:
      #   what: infused-kim/switch_power
      #   where:
      #     ref: power
      #   params: 
      #     reverse: true
      #     from: BAT_P
      #     to: RAW
      # reset:
      #   what: reset_switch # footprint from celoide's corney-island
        # where:
          # ref: reset
          # rotate: -90 # -90 = right facing
        # params:
          # from: RST
          # to: GND
      # m2_screws:
        # what: screw_hole
        # where: /screw_pcb/
        # params:
          # size: scd
          # drill: scd
      # trrs:
        # what: trrs_ceo
        # where:
          # ref: trrs
          # rotate: -90
        # params:
          # reversible: true
          # symmetric: true
          # A: SP # interconnect pin
          # C: GND
          # D: VCC
